export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT = 'USER_SIGNOUT';




export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';


export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';



export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';




export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';
export const USER_DELETE_RESET = 'USER_DELETE_RESET';


//for admins
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';


export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';



export const LIKE_REQUEST = 'LIKE_REQUEST';
export const LIKE_SUCCESS = 'LIKE_SUCCESS';
export const LIKE_FAIL = 'LIKE_FAIL';
export const LIKE_RESET = 'LIKE_RESET';



export const LIST_USERS_BY_ID_REQUEST = 'LIST_USERS_BY_ID_REQUEST';
export const LIST_USERS_BY_ID_SUCCUESS = 'LIST_USERS_BY_ID_SUCCUESS';
export const LIST_USERS_BY_ID_FAIL = 'LIST_USERS_BY_ID_FAIL';


export const REMOVER_REQUEST = 'REMOVER_REQUEST';
export const REMOVER_SUCCESS = 'REMOVER_SUCCESS';
export const REMOVER_FAIL = 'REMOVER_FAIL';
export const REMOVER_RESET = 'REMOVER_RESET';



export const MAX_LIMIT_REACHED = 'MAX_LIMIT_REACHED';
export const MAX_LIMIT_NOT_REACHED = 'MAX_LIMIT_NOT_REACHED';





export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
export const ACCEPT_SUCCESS = 'ACCEPT_SUCCESS';
export const ACCEPT_FAIL = 'ACCEPT_FAIL';

export const REJECT_REQUEST = 'REJECT_REQUEST';
export const REJECT_SUCCESS = 'REJECT_SUCCESS';
export const REJECT_FAIL = 'REJECT_FAIL';

export const LIST_OTHERSLIKE_REQUEST = 'LIST_OTHERSLIKE_REQUEST';
export const LIST_OTHERSLIKE_SUCCESS = 'LIST_OTHERSLIKE_SUCCESS';
export const LIST_OTHERSLIKE_FAIL = 'LIST_OTHERSLIKE_FAIL';

export const LIST_FORCHAT_REQUEST = 'LIST_FORCHAT_REQUEST';
export const LIST_FORCHAT_SUCCESS = 'LIST_FORCHAT_SUCCESS';
export const LIST_FORCHAT_FAIL = 'LIST_FORCHAT_FAIL';
